name: Build FairyChat

on:
  workflow_dispatch:
  push:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle (shadowJar)
        run: ./gradlew clean shadowJar

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: FairyChat
          path: build/libs/FairyChat-*.jar
